# .github/workflows/deploy.yml
name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Debug step to ensure GCP_SERVICE_ACCOUNT is available
    - name: Debug GCP_SERVICE_ACCOUNT variable
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        if [ -z "$GCP_SERVICE_ACCOUNT" ]; then
          echo "ERROR: GCP_SERVICE_ACCOUNT is not set!"
          exit 1
        else
          echo "SUCCESS: GCP_SERVICE_ACCOUNT is set."
        fi

    # Create service account JSON file if GCP_SERVICE_ACCOUNT is set
    - name: Prepare Service Account JSON file
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        if [ -n "$GCP_SERVICE_ACCOUNT" ]; then
          echo "$GCP_SERVICE_ACCOUNT" > service_account.json
          echo "Service account JSON file created."
        else
          echo "GCP_SERVICE_ACCOUNT is not set. Exiting."
          exit 1
        fi

    # Run Streamlit App
    - name: Run Streamlit App
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        streamlit run app.py
