# .github/workflows/deploy.yml
name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Check if the GCP_SERVICE_ACCOUNT secret is available and display status
    - name: Check GCP_SERVICE_ACCOUNT availability
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        if [ -z "$GCP_SERVICE_ACCOUNT" ]; then
          echo "ERROR: GCP_SERVICE_ACCOUNT is not set!"
          exit 1
        else
          echo "SUCCESS: GCP_SERVICE_ACCOUNT is set."
          echo "$GCP_SERVICE_ACCOUNT" | head -c 100  # Print only the first 100 characters to avoid exposing sensitive data
        fi

    # Create service account JSON file from GCP_SERVICE_ACCOUNT
    - name: Prepare Service Account JSON file
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        if [ -n "$GCP_SERVICE_ACCOUNT" ]; then
          echo "$GCP_SERVICE_ACCOUNT" > service_account.json
          echo "Service account JSON file created."
        else
          echo "GCP_SERVICE_ACCOUNT is not set. Exiting."
          exit 1
        fi

    # Run Streamlit App
    - name: Run Streamlit App
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: |
        streamlit run app.py
